apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook.fullname" . }}
  labels: {{ include "webhook.labels" . | nindent 4 }}
type: Opaque
stringData:
  api_key: {{ .Values.webhook.apiKey }}
  deploy_key: |
{{ .Values.repo.deployKey }}
  {{- if .Values.vault.enabled }}
  vault_secret_id: {{ .Values.vault.secretId }}
  {{- end }}
  {{- if .Values.f5.enabled }}
  f5_password: {{ (index .Values.f5.hosts 0).password }}
  {{- end }}
