apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme-webhook
namePrefix: acme-

commonLabels:
  app.kubernetes.io/name: acme-git-webhook
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
